# tasks file for azure-aks
- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ AKS_resource_group }}"
    location: "{{ AKS_location }}"
- name: Create an AKS cluster
  azure_rm_aks:
    name: "{{ aks_name }}"
    location: "{{ AKS_location }}"
    kubernetes_version: "{{ k8s_version }}"
    resource_group: "{{ AKS_resource_group }}"
    dns_prefix: "mynewcluster"
    linux_profile:
      admin_username: "{{ username }}"
      ssh_key: "{{ ssh_pub_key }}"
    service_principal:
      client_id: "{{ client_id }}"
      client_secret: "{{ client_secret }}"
    agent_pool_profiles:
      - name: default
        count: 3
        vm_size: "{{ node_size }}"
    tags:
      Environment: "Dev"
      Backup: "False"
      Client: "Vijay"
